# Caixaverso - FC2 | Analista de Dados
## Projeto para o curso Técnicas de Programação I (PY) do 

### Aluno: Renato Tomio Yodono

In [1]:
# Importando bibliotecas
import pandas as pd
import numpy as np

In [2]:
# Lendo o arquivo e salvando numa variável
df = pd.read_csv("UCI_Credit_Card.csv")

# Obtido em https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/
# em 17/04/2026

In [3]:
# Visão inicial do dataset
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [4]:
# Consultando o número de linhas, colunas, tipos e nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [5]:
df.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

### Início do Data Wrangling

In [6]:
# Excluindo a coluna ID, pois não contribuirá com a análise
df.drop(columns=['ID'], inplace=True)

In [7]:
# Alterando o nome das colunas para português

df.columns = ['LIMITE_DO_CARTAO',
              'SEXO',
              'ESCOLARIDADE',
              'ESTADO_CIVIL',
              'IDADE',
              'STATUS_PAGAMENTO_0',
              'STATUS_PAGAMENTO_2',
              'STATUS_PAGAMENTO_3',
              'STATUS_PAGAMENTO_4',
              'STATUS_PAGAMENTO_5',
              'STATUS_PAGAMENTO_6',
              'VALOR_DA_FATURA_1',
              'VALOR_DA_FATURA_2',
              'VALOR_DA_FATURA_3',
              'VALOR_DA_FATURA_4',
              'VALOR_DA_FATURA_5',
              'VALOR_DA_FATURA_6',
              'VALOR_PAGO_1',
              'VALOR_PAGO_2',
              'VALOR_PAGO_3',
              'VALOR_PAGO_4',
              'VALOR_PAGO_5',
              'VALOR_PAGO_6',
              'INADIMPLENTE']

In [8]:
# Dicionário de dados, conforme fornecido pelo Kaggle, para verificação de valores inválidos para as variáveis categóricas
# As atribuições abaixo foram baseadas nas informações fornecidaas no Kaggle nos links abaixo:
# https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset
# https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/discussion/34608

valores_validos = {'SEXO': [1,2],
                   'ESCOLARIDADE': [1,2,3,4],
                   'ESTADO_CIVIL': [0,1,2,3],
                   'STATUS_PAGAMENTO_0': list(range(-2,10)),
                   'STATUS_PAGAMENTO_2': list(range(-2,10)),
                   'STATUS_PAGAMENTO_3': list(range(-2,10)),
                   'STATUS_PAGAMENTO_4': list(range(-2,10)),
                   'STATUS_PAGAMENTO_5': list(range(-2,10)),
                   'STATUS_PAGAMENTO_6': list(range(-2,10)),
                   'INADIMPLENTE': [0,1]}

# Tratamento a ser dado aos valores inválidos das variáveis categóricas:
    
    # SEXO: atribuir nan
    # ESCOLARIDADE: atribuir o valor 4 (outros)
    # ESTADO-CIVIL: atribuir o valor 0 (outros)
    # STATUS_PAGAMENTO_0: atribuir nan
    # STATUS_PAGAMENTO_2: atribuir nan
    # STATUS_PAGAMENTO_3: atribuir nan
    # STATUS_PAGAMENTO_4: atribuir nan
    # STATUS_PAGAMENTO_5: atribuir nan
    # STATUS_PAGAMENTO_6: atribuir nan
    # INADIMPLENTE: atribuir nan

tratar_valores_invalidos = {'SEXO': np.nan,
                   'ESCOLARIDADE': 4,
                   'ESTADO_CIVIL': 0,
                   'STATUS_PAGAMENTO_0': np.nan,
                   'STATUS_PAGAMENTO_2': np.nan,
                   'STATUS_PAGAMENTO_3': np.nan,
                   'STATUS_PAGAMENTO_4': np.nan,
                   'STATUS_PAGAMENTO_5': np.nan,
                   'STATUS_PAGAMENTO_6': np.nan,
                   'INADIMPLENTE': np.nan}

# Para as variáveis quantitativas definiremos como valores válidos:

    # IDADE: maior que 18 e menor que 120
        #Tratamento a ser dado: atribuir nan

    # LIMITE_DO_CARTAO: maior ou igual a zero
    # VALOR_DA_FATURA_1: maior ou igual a zero
    # VALOR_DA_FATURA_2: maior ou igual a zero
    # VALOR_DA_FATURA_3: maior ou igual a zero
    # VALOR_DA_FATURA_4: maior ou igual a zero
    # VALOR_DA_FATURA_5: maior ou igual a zero
    # VALOR_DA_FATURA_6: maior ou igual a zero
    # VALOR_PAGO_1: maior ou igual a zero
    # VALOR_PAGO_2: maior ou igual a zero
    # VALOR_PAGO_3: maior ou igual a zero
    # VALOR_PAGO_4: maior ou igual a zero
    # VALOR_PAGO_5: maior ou igual a zero
    # VALOR_PAGO_6: maior ou igual a zero

    # Tratamento a ser dado ao valores inválidos: atribuir zero

variaveis_quantitativas = ['LIMITE_DO_CARTAO',
                           'VALOR_DA_FATURA_1',
                           'VALOR_DA_FATURA_2',
                           'VALOR_DA_FATURA_3',
                           'VALOR_DA_FATURA_4',
                           'VALOR_DA_FATURA_5',
                           'VALOR_DA_FATURA_6',
                           'VALOR_PAGO_1',
                           'VALOR_PAGO_2',
                           'VALOR_PAGO_3',
                           'VALOR_PAGO_4',
                           'VALOR_PAGO_5',
                           'VALOR_PAGO_6']

In [9]:
# Tratamento de valores inválidos

for coluna, valor in valores_validos.items():
    df.loc[~(df[coluna].isin(valor)), coluna] = tratar_valores_invalidos[coluna]

df.loc[(df['IDADE'] < 18) | (df['IDADE'] > 120), 'IDADE'] = np.nan

for coluna in variaveis_quantitativas:
    df.loc[df[coluna] < 0, coluna] = 0